package og;

import java.awt.Color;
import javax.swing.ImageIcon;
import BasesDatos.SQLConectar;
import Logica.Funciones;
import ModPersona.funcionesPersona;
import ModPersona.Usuario;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class GUI_START extends javax.swing.JFrame {

    private File archivoActual;
    private String url;

    public GUI_START() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/iconos/ogchikito.png")).getImage());
        deco.setVisible(true);
        iniciar.setVisible(true);
        menu.setVisible(false);
        panel_notas.setVisible(false);
        panel_user.setVisible(false);
        panel_cal.setVisible(false);
        panel_opciones.setVisible(false);
        panel_final.setVisible(false);
        SQLConectar.SQL_Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        up_panel = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        opcion_final = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        showuser = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BtnAbrirNotas = new javax.swing.JButton();
        opcion_user = new javax.swing.JButton();
        opcion_cal = new javax.swing.JButton();
        opcion_settings = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        iniciar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        emailField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        BtnEntrarLogin = new javax.swing.JPanel();
        entrar = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        empecemos = new javax.swing.JLabel();
        salirpanel = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        advertenciaLabel = new javax.swing.JLabel();
        deco = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PanelAbrirNotas = new javax.swing.JPanel();
        panel_notas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtA_contentNota = new javax.swing.JTextArea();
        Lbl_tituloNota = new javax.swing.JLabel();
        Lbl_categoria = new javax.swing.JLabel();
        BtnGuardarNota = new javax.swing.JButton();
        BtnAbrirNota1 = new javax.swing.JButton();
        BtnFiltrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        Txt_categoria = new javax.swing.JTextField();
        panel_user = new javax.swing.JPanel();
        panel_cal = new javax.swing.JPanel();
        panel_opciones = new javax.swing.JPanel();
        panel_final = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OGNOTE");
        setBounds(new java.awt.Rectangle(20, 20, 20, 20));
        setPreferredSize(new java.awt.Dimension(910, 530));

        up_panel.setBackground(new java.awt.Color(0, 153, 153));
        up_panel.setPreferredSize(new java.awt.Dimension(910, 540));
        up_panel.setLayout(null);

        menu.setBackground(new java.awt.Color(166, 195, 192));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opcion_final.setBackground(new java.awt.Color(166, 195, 192));
        opcion_final.setForeground(new java.awt.Color(8, 59, 8));
        opcion_final.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Speech Bubble_1.png"))); // NOI18N
        opcion_final.setText("Acerca de...");
        opcion_final.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        opcion_final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_finalActionPerformed(evt);
            }
        });
        menu.add(opcion_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 160, 40));

        Exit.setBackground(new java.awt.Color(204, 255, 255));
        Exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Exit.setText("SALIR");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        menu.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 170, 40));

        showuser.setBackground(new java.awt.Color(204, 204, 204));
        showuser.setToolTipText("");
        showuser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        showuser.setName(""); // NOI18N
        showuser.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/foto2.png"))); // NOI18N
        showuser.add(jLabel8);
        jLabel8.setBounds(0, 10, 100, 80);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Usuario:");
        showuser.add(jLabel10);
        jLabel10.setBounds(100, 20, 60, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Admin");
        showuser.add(jLabel11);
        jLabel11.setBounds(110, 50, 43, 16);

        menu.add(showuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 190, 100));

        BtnAbrirNotas.setBackground(new java.awt.Color(166, 195, 192));
        BtnAbrirNotas.setForeground(new java.awt.Color(8, 59, 8));
        BtnAbrirNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Sticky Notes_1.png"))); // NOI18N
        BtnAbrirNotas.setText("Notas");
        BtnAbrirNotas.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        BtnAbrirNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAbrirNotasActionPerformed(evt);
            }
        });
        menu.add(BtnAbrirNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 40));

        opcion_user.setBackground(new java.awt.Color(166, 195, 192));
        opcion_user.setForeground(new java.awt.Color(8, 59, 8));
        opcion_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/User Male.png"))); // NOI18N
        opcion_user.setText("Usuario");
        opcion_user.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        opcion_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_userActionPerformed(evt);
            }
        });
        menu.add(opcion_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, 40));

        opcion_cal.setBackground(new java.awt.Color(166, 195, 192));
        opcion_cal.setForeground(new java.awt.Color(8, 59, 8));
        opcion_cal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Google Calendar.png"))); // NOI18N
        opcion_cal.setText("Calendario");
        opcion_cal.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        opcion_cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_calActionPerformed(evt);
            }
        });
        menu.add(opcion_cal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, 40));

        opcion_settings.setBackground(new java.awt.Color(166, 195, 192));
        opcion_settings.setForeground(new java.awt.Color(8, 59, 8));
        opcion_settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Settings_1.png"))); // NOI18N
        opcion_settings.setText("Opciones");
        opcion_settings.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        opcion_settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_settingsActionPerformed(evt);
            }
        });
        menu.add(opcion_settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 160, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Ogicon.png"))); // NOI18N
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, 210, 120));

        up_panel.add(menu);
        menu.setBounds(0, 0, 220, 510);

        iniciar.setPreferredSize(new java.awt.Dimension(400, 0));
        iniciar.setLayout(null);

        jPanel4.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Google_2.png"))); // NOI18N
        jButton1.setText(" Iniciar sesión con Google");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setPreferredSize(new java.awt.Dimension(250, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        iniciar.add(jPanel4);
        jPanel4.setBounds(0, 112, 400, 50);

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("BIENVENIDOG");
        jLabel1.setInheritsPopupMenu(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(151, 151, 151))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        iniciar.add(jPanel3);
        jPanel3.setBounds(0, 50, 400, 50);

        jPanel5.setPreferredSize(new java.awt.Dimension(400, 150));

        jPanel7.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel7.setLayout(new java.awt.BorderLayout(0, 4));

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        jPanel7.add(emailField, java.awt.BorderLayout.CENTER);

        jLabel3.setText("Correo");
        jPanel7.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jPanel6.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel6.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel2.setText("Contraseña");
        jPanel6.add(jLabel2, java.awt.BorderLayout.PAGE_START);
        jPanel6.add(passwordField, java.awt.BorderLayout.CENTER);

        jPanel8.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jCheckBox1.setText("Recordarme");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel8.add(jCheckBox1, java.awt.BorderLayout.WEST);

        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Olvidaste tu contraseña?");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel8.add(jLabel4, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        iniciar.add(jPanel5);
        jPanel5.setBounds(0, 168, 399, 150);

        BtnEntrarLogin.setPreferredSize(new java.awt.Dimension(400, 50));

        entrar.setText("ENTRAR");
        entrar.setPreferredSize(new java.awt.Dimension(250, 30));
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BtnEntrarLoginLayout = new javax.swing.GroupLayout(BtnEntrarLogin);
        BtnEntrarLogin.setLayout(BtnEntrarLoginLayout);
        BtnEntrarLoginLayout.setHorizontalGroup(
            BtnEntrarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnEntrarLoginLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(entrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BtnEntrarLoginLayout.setVerticalGroup(
            BtnEntrarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnEntrarLoginLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(entrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        iniciar.add(BtnEntrarLogin);
        BtnEntrarLogin.setBounds(0, 336, 400, 50);

        jPanel10.setPreferredSize(new java.awt.Dimension(400, 50));

        jLabel5.setText("No tienes una cuenta aún?");

        empecemos.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        empecemos.setText("Empecemos!");
        empecemos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empecemos(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empecemosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                empecemosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(empecemos))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(empecemos)))
        );

        iniciar.add(jPanel10);
        jPanel10.setBounds(0, 392, 400, 50);

        salirpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirpanelMouseEntered(evt);
            }
        });

        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Close.png"))); // NOI18N
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout salirpanelLayout = new javax.swing.GroupLayout(salirpanel);
        salirpanel.setLayout(salirpanelLayout);
        salirpanelLayout.setHorizontalGroup(
            salirpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salirpanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        salirpanelLayout.setVerticalGroup(
            salirpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salirpanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        iniciar.add(salirpanel);
        salirpanel.setBounds(0, 0, 40, 40);

        advertenciaLabel.setForeground(new java.awt.Color(255, 102, 102));
        iniciar.add(advertenciaLabel);
        advertenciaLabel.setBounds(80, 320, 240, 16);

        up_panel.add(iniciar);
        iniciar.setBounds(0, 0, 408, 510);

        deco.setBackground(new java.awt.Color(166, 195, 192));
        deco.setPreferredSize(new java.awt.Dimension(400, 430));
        deco.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/otro.png"))); // NOI18N
        deco.add(jLabel6);
        jLabel6.setBounds(110, 150, 300, 179);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Ogicon.png"))); // NOI18N
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deco.add(jLabel12);
        jLabel12.setBounds(-100, -70, 280, 230);

        up_panel.add(deco);
        deco.setBounds(400, 0, 530, 510);

        PanelAbrirNotas.setBackground(new java.awt.Color(0, 153, 153));
        PanelAbrirNotas.setLayout(new java.awt.CardLayout());

        panel_notas.setBackground(new java.awt.Color(0, 153, 153));

        TxtA_contentNota.setColumns(20);
        TxtA_contentNota.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TxtA_contentNota.setRows(5);
        jScrollPane2.setViewportView(TxtA_contentNota);

        Lbl_tituloNota.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 14)); // NOI18N

        Lbl_categoria.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Lbl_categoria.setText("Categoria:");

        BtnGuardarNota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnGuardarNota.setText("Guardar");
        BtnGuardarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarNotaActionPerformed(evt);
            }
        });

        BtnAbrirNota1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnAbrirNota1.setText("Abrir");
        BtnAbrirNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAbrirNota1ActionPerformed(evt);
            }
        });

        BtnFiltrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnFiltrar.setText("filtrar por categoria");
        BtnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFiltrarActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Txt_categoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Txt_categoria.setText("Digite  la categoria de su nota aquí...");
        Txt_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_categoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_notasLayout = new javax.swing.GroupLayout(panel_notas);
        panel_notas.setLayout(panel_notasLayout);
        panel_notasLayout.setHorizontalGroup(
            panel_notasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(panel_notasLayout.createSequentialGroup()
                .addGroup(panel_notasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_notasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lbl_tituloNota, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_notasLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panel_notasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_notasLayout.createSequentialGroup()
                                .addGroup(panel_notasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel_notasLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(Lbl_categoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(8, 8, 8))
                            .addGroup(panel_notasLayout.createSequentialGroup()
                                .addComponent(BtnAbrirNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(BtnGuardarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnFiltrar)
                                .addGap(16, 16, 16)))))
                .addGap(74, 74, Short.MAX_VALUE))
        );
        panel_notasLayout.setVerticalGroup(
            panel_notasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_notasLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(Lbl_tituloNota, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Lbl_categoria)
                .addGap(18, 18, 18)
                .addGroup(panel_notasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(Txt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(panel_notasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardarNota)
                    .addComponent(BtnAbrirNota1)
                    .addComponent(BtnFiltrar))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        PanelAbrirNotas.add(panel_notas, "card4");

        panel_user.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout panel_userLayout = new javax.swing.GroupLayout(panel_user);
        panel_user.setLayout(panel_userLayout);
        panel_userLayout.setHorizontalGroup(
            panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        panel_userLayout.setVerticalGroup(
            panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        PanelAbrirNotas.add(panel_user, "card5");

        panel_cal.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout panel_calLayout = new javax.swing.GroupLayout(panel_cal);
        panel_cal.setLayout(panel_calLayout);
        panel_calLayout.setHorizontalGroup(
            panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        panel_calLayout.setVerticalGroup(
            panel_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        PanelAbrirNotas.add(panel_cal, "card7");

        panel_opciones.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout panel_opcionesLayout = new javax.swing.GroupLayout(panel_opciones);
        panel_opciones.setLayout(panel_opcionesLayout);
        panel_opcionesLayout.setHorizontalGroup(
            panel_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        panel_opcionesLayout.setVerticalGroup(
            panel_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        PanelAbrirNotas.add(panel_opciones, "card3");

        panel_final.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout panel_finalLayout = new javax.swing.GroupLayout(panel_final);
        panel_final.setLayout(panel_finalLayout);
        panel_finalLayout.setHorizontalGroup(
            panel_finalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        panel_finalLayout.setVerticalGroup(
            panel_finalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        PanelAbrirNotas.add(panel_final, "card6");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        PanelAbrirNotas.add(jPanel11, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(up_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(213, Short.MAX_VALUE)
                    .addComponent(PanelAbrirNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(up_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(PanelAbrirNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirpanelMouseEntered

    }//GEN-LAST:event_salirpanelMouseEntered

    private void salirpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirpanelMouseClicked

    }//GEN-LAST:event_salirpanelMouseClicked

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        salirpanel.setBackground(new java.awt.Color(238, 238, 238));
    }//GEN-LAST:event_salirMouseExited

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        salirpanel.setBackground(Color.red);
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void empecemosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empecemosMouseExited
        empecemos.setForeground(Color.black);
    }//GEN-LAST:event_empecemosMouseExited

    private void empecemosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empecemosMouseEntered
        empecemos.setForeground(new java.awt.Color(0, 102, 54));
    }//GEN-LAST:event_empecemosMouseEntered

    private void empecemos(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empecemos
        this.setVisible(false);
        registro fl = new registro();
        fl.setVisible(true);
    }//GEN-LAST:event_empecemos

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        String email = emailField.getText();
        String password = new String(passwordField.getPassword());
        if (!email.isBlank() && !password.isBlank()) {
            if (SQLConectar.verificar(email, password)) {
                deco.setVisible(false);
                iniciar.setVisible(false);
                menu.setVisible(true);
                Usuario temp = new Usuario();
                temp.setID(Integer.parseInt(SQLConectar.getID()));
                url = temp.getUrl();
            } else {
                advertenciaLabel.setText("Correo o contraseña incorrectos");
            }
        } else {
            advertenciaLabel.setText("Hay campos vacios");
        }


    }//GEN-LAST:event_entrarActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void BtnAbrirNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAbrirNotasActionPerformed
        panel_notas.setVisible(true);
        panel_user.setVisible(false);
        panel_cal.setVisible(false);
        panel_opciones.setVisible(false);
        panel_final.setVisible(false);
    }//GEN-LAST:event_BtnAbrirNotasActionPerformed

    private void opcion_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_userActionPerformed
        panel_notas.setVisible(false);
        panel_user.setVisible(true);
        panel_cal.setVisible(false);
        panel_opciones.setVisible(false);
        panel_final.setVisible(false);


    }//GEN-LAST:event_opcion_userActionPerformed

    private void opcion_finalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_finalActionPerformed
        panel_notas.setVisible(false);
        panel_user.setVisible(false);
        panel_cal.setVisible(false);
        panel_opciones.setVisible(false);
        panel_final.setVisible(true);
    }//GEN-LAST:event_opcion_finalActionPerformed

    private void opcion_calActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_calActionPerformed
        panel_notas.setVisible(false);
        panel_user.setVisible(false);
        panel_cal.setVisible(true);
        panel_opciones.setVisible(false);
        panel_final.setVisible(false);
    }//GEN-LAST:event_opcion_calActionPerformed

    private void opcion_settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_settingsActionPerformed
        panel_notas.setVisible(false);
        panel_user.setVisible(false);
        panel_cal.setVisible(false);
        panel_opciones.setVisible(true);
        panel_final.setVisible(false);
    }//GEN-LAST:event_opcion_settingsActionPerformed

    private void BtnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnFiltrarActionPerformed

    private void BtnAbrirNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAbrirNota1ActionPerformed
        JFileChooser archivo = new JFileChooser();
        archivo.setFileHidingEnabled(true);
        File workingDirectory = new File(url);

        archivo.setCurrentDirectory(workingDirectory);

        FileNameExtensionFilter filtroTxt = new FileNameExtensionFilter("Archivos de texto (.txt)", "txt");
        archivo.setFileFilter(filtroTxt);

        Funciones conteo = new Funciones();

        if (conteo.Num_Notas(url) > 0) {
            int seleccion = archivo.showOpenDialog(this.getContentPane());

            if (seleccion == JFileChooser.APPROVE_OPTION) {
                this.archivoActual = archivo.getSelectedFile();
                
                try {
                    if (archivoActual.getCanonicalPath().equals(url + "\\" + archivoActual.getName())) {
                        TxtA_contentNota.setText("");
                        Scanner myReader = new Scanner(archivo.getSelectedFile());
                        while (myReader.hasNextLine()) {
                            String data = myReader.nextLine();
                            if ("".equals(TxtA_contentNota.getText())) {
                                TxtA_contentNota.setText(data);
                            } else {
                                TxtA_contentNota.setText(TxtA_contentNota.getText() + "\n" + data);
                            }

                            String[] nombreArchivoTemp = (archivo.getSelectedFile().getName()).split(".txt");
                            Lbl_tituloNota.setText(nombreArchivoTemp[0].toUpperCase());
//                            System.out.println(data);
                        }
                        myReader.close();
                        String filePath = archivo.getSelectedFile().getAbsolutePath();
                        Path path = Paths.get(filePath);
                        Files.setAttribute(path, "dos:hidden", false, LinkOption.NOFOLLOW_LINKS);
                        this.archivoActual.setWritable(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "No puede acceder a otra ruta que no sea propia ");
                    }
                } catch (IOException err) {

                }

            }

            //archivo.setCurrentDirectory();
        } else {
            AdvertenciaNotasNUll advertencia = new AdvertenciaNotasNUll(this, true);
            advertencia.setVisible(true);
        }
    }//GEN-LAST:event_BtnAbrirNota1ActionPerformed

    private void BtnGuardarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarNotaActionPerformed
        // TODO add your handling code here:
        JFileChooser archivo = new JFileChooser();
        archivo.setFileHidingEnabled(true);
        File workingDirectory = new File(url);

        archivo.setCurrentDirectory(workingDirectory);

        FileNameExtensionFilter filtroTxt = new FileNameExtensionFilter("Archivos de texto (.txt)", "txt");
        archivo.setFileFilter(filtroTxt);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto (.txt)", "txt");
        int returnVal = archivo.showSaveDialog(GUI_START.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String filePath = archivo.getSelectedFile().getAbsolutePath();
            try {

                archivoActual = new File(filePath);

                if (!archivoActual.exists()) {
                    FileWriter tempFile = new FileWriter(filePath);
                    System.out.println("Archivo creado: " + archivoActual.getName());
                    tempFile.write(TxtA_contentNota.getText());
                    tempFile.close();
                } else {
                    System.out.println("Archivo ya existente.");
                }

            } catch (IOException err) {
                System.out.println("An error occurred.");
                err.printStackTrace();
            }
        } else {
            System.out.println("Error");
        }
    }//GEN-LAST:event_BtnGuardarNotaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.TxtA_contentNota.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Txt_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_categoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAbrirNota1;
    private javax.swing.JButton BtnAbrirNotas;
    private javax.swing.JPanel BtnEntrarLogin;
    private javax.swing.JButton BtnFiltrar;
    private javax.swing.JButton BtnGuardarNota;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Lbl_categoria;
    private javax.swing.JLabel Lbl_tituloNota;
    private javax.swing.JPanel PanelAbrirNotas;
    private javax.swing.JTextArea TxtA_contentNota;
    private javax.swing.JTextField Txt_categoria;
    private javax.swing.JLabel advertenciaLabel;
    private javax.swing.JPanel deco;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel empecemos;
    private javax.swing.JButton entrar;
    private javax.swing.JPanel iniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menu;
    private javax.swing.JButton opcion_cal;
    private javax.swing.JButton opcion_final;
    private javax.swing.JButton opcion_settings;
    private javax.swing.JButton opcion_user;
    private javax.swing.JPanel panel_cal;
    private javax.swing.JPanel panel_final;
    private javax.swing.JPanel panel_notas;
    private javax.swing.JPanel panel_opciones;
    private javax.swing.JPanel panel_user;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel salir;
    private javax.swing.JPanel salirpanel;
    private javax.swing.JPanel showuser;
    private javax.swing.JPanel up_panel;
    // End of variables declaration//GEN-END:variables
}
